// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: fancy_painter.proto

package fancy_painter

import (
	fancy_common "github.com/akatsukisun2020/fancy_painter/proto/fancy_common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // 支持的token
}

func (x *UserLoginReq) Reset() {
	*x = UserLoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fancy_painter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginReq) ProtoMessage() {}

func (x *UserLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_fancy_painter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginReq.ProtoReflect.Descriptor instead.
func (*UserLoginReq) Descriptor() ([]byte, []int) {
	return file_fancy_painter_proto_rawDescGZIP(), []int{0}
}

func (x *UserLoginReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                // 用户id
	PhoneNumber string `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"` // 电话号码
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fancy_painter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_fancy_painter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_fancy_painter_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserInfo) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type UserLoginRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RetCode int32  `protobuf:"varint,1,opt,name=ret_code,json=retCode,proto3" json:"ret_code,omitempty"`
	RetMsg  string `protobuf:"bytes,2,opt,name=ret_msg,json=retMsg,proto3" json:"ret_msg,omitempty"`
	UserId  string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 内部用户id
}

func (x *UserLoginRsp) Reset() {
	*x = UserLoginRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fancy_painter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserLoginRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginRsp) ProtoMessage() {}

func (x *UserLoginRsp) ProtoReflect() protoreflect.Message {
	mi := &file_fancy_painter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginRsp.ProtoReflect.Descriptor instead.
func (*UserLoginRsp) Descriptor() ([]byte, []int) {
	return file_fancy_painter_proto_rawDescGZIP(), []int{2}
}

func (x *UserLoginRsp) GetRetCode() int32 {
	if x != nil {
		return x.RetCode
	}
	return 0
}

func (x *UserLoginRsp) GetRetMsg() string {
	if x != nil {
		return x.RetMsg
	}
	return ""
}

func (x *UserLoginRsp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

//请求
type UserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UserReq) Reset() {
	*x = UserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fancy_painter_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReq) ProtoMessage() {}

func (x *UserReq) ProtoReflect() protoreflect.Message {
	mi := &file_fancy_painter_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReq.ProtoReflect.Descriptor instead.
func (*UserReq) Descriptor() ([]byte, []int) {
	return file_fancy_painter_proto_rawDescGZIP(), []int{3}
}

func (x *UserReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

//响应
type UserRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UserRsp) Reset() {
	*x = UserRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fancy_painter_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRsp) ProtoMessage() {}

func (x *UserRsp) ProtoReflect() protoreflect.Message {
	mi := &file_fancy_painter_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRsp.ProtoReflect.Descriptor instead.
func (*UserRsp) Descriptor() ([]byte, []int) {
	return file_fancy_painter_proto_rawDescGZIP(), []int{4}
}

func (x *UserRsp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

//绘制图片请求
type SmartDrawImgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhoneNumber      string                         `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`                    // 电话号码
	UserId           string                         `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                   // 内部用户id，类似秘钥
	SmartDrawImgTask *fancy_common.SmartDrawImgTask `protobuf:"bytes,3,opt,name=smart_draw_img_task,json=smartDrawImgTask,proto3" json:"smart_draw_img_task,omitempty"` // 智能画图任务
}

func (x *SmartDrawImgReq) Reset() {
	*x = SmartDrawImgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fancy_painter_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmartDrawImgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmartDrawImgReq) ProtoMessage() {}

func (x *SmartDrawImgReq) ProtoReflect() protoreflect.Message {
	mi := &file_fancy_painter_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmartDrawImgReq.ProtoReflect.Descriptor instead.
func (*SmartDrawImgReq) Descriptor() ([]byte, []int) {
	return file_fancy_painter_proto_rawDescGZIP(), []int{5}
}

func (x *SmartDrawImgReq) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *SmartDrawImgReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SmartDrawImgReq) GetSmartDrawImgTask() *fancy_common.SmartDrawImgTask {
	if x != nil {
		return x.SmartDrawImgTask
	}
	return nil
}

//绘制图片响应
type SmartDrawImgRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RetCode int32  `protobuf:"varint,1,opt,name=ret_code,json=retCode,proto3" json:"ret_code,omitempty"`
	RetMsg  string `protobuf:"bytes,2,opt,name=ret_msg,json=retMsg,proto3" json:"ret_msg,omitempty"`
}

func (x *SmartDrawImgRsp) Reset() {
	*x = SmartDrawImgRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fancy_painter_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmartDrawImgRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmartDrawImgRsp) ProtoMessage() {}

func (x *SmartDrawImgRsp) ProtoReflect() protoreflect.Message {
	mi := &file_fancy_painter_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmartDrawImgRsp.ProtoReflect.Descriptor instead.
func (*SmartDrawImgRsp) Descriptor() ([]byte, []int) {
	return file_fancy_painter_proto_rawDescGZIP(), []int{6}
}

func (x *SmartDrawImgRsp) GetRetCode() int32 {
	if x != nil {
		return x.RetCode
	}
	return 0
}

func (x *SmartDrawImgRsp) GetRetMsg() string {
	if x != nil {
		return x.RetMsg
	}
	return ""
}

var File_fancy_painter_proto protoreflect.FileDescriptor

var file_fancy_painter_proto_rawDesc = []byte{
	0x0a, 0x13, 0x66, 0x61, 0x6e, 0x63, 0x79, 0x5f, 0x70, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x78, 0x67, 0x72, 0x70, 0x63, 0x64, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x66, 0x61, 0x6e,
	0x63, 0x79, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x66, 0x61, 0x6e, 0x63, 0x79, 0x5f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x24, 0x0a, 0x0c,
	0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x22, 0x46, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x5b, 0x0a, 0x0c, 0x55, 0x73,
	0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x65,
	0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65,
	0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x5f, 0x6d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x19, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x1d, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x9b, 0x01, 0x0a, 0x0f, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x44, 0x72, 0x61, 0x77, 0x49,
	0x6d, 0x67, 0x52, 0x65, 0x71, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f,
	0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x4c, 0x0a, 0x13, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x5f, 0x64, 0x72, 0x61, 0x77, 0x5f,
	0x69, 0x6d, 0x67, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x66, 0x61, 0x6e, 0x63, 0x79, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x6d, 0x61,
	0x72, 0x74, 0x44, 0x72, 0x61, 0x77, 0x49, 0x6d, 0x67, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x10, 0x73,
	0x6d, 0x61, 0x72, 0x74, 0x44, 0x72, 0x61, 0x77, 0x49, 0x6d, 0x67, 0x54, 0x61, 0x73, 0x6b, 0x22,
	0x45, 0x0a, 0x0f, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x44, 0x72, 0x61, 0x77, 0x49, 0x6d, 0x67, 0x52,
	0x73, 0x70, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x65, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x17, 0x0a,
	0x07, 0x72, 0x65, 0x74, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x74, 0x4d, 0x73, 0x67, 0x32, 0xa7, 0x02, 0x0a, 0x0c, 0x46, 0x61, 0x6e, 0x63, 0x79,
	0x50, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x4c, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x12, 0x0f, 0x2e, 0x78, 0x67, 0x72, 0x70, 0x63, 0x64, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x78, 0x67, 0x72, 0x70, 0x63, 0x64, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x73, 0x70, 0x22, 0x1f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x19, 0x12, 0x17, 0x2f, 0x66,
	0x61, 0x6e, 0x63, 0x79, 0x5f, 0x70, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x2f, 0x67, 0x65, 0x74,
	0x5f, 0x75, 0x73, 0x65, 0x72, 0x12, 0x5d, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x12, 0x14, 0x2e, 0x78, 0x67, 0x72, 0x70, 0x63, 0x64, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x78, 0x67, 0x72, 0x70, 0x63,
	0x64, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x73, 0x70, 0x22, 0x24,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1e, 0x22, 0x19, 0x2f, 0x66, 0x61, 0x6e, 0x63, 0x79, 0x5f, 0x70,
	0x61, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67, 0x69,
	0x6e, 0x3a, 0x01, 0x2a, 0x12, 0x6a, 0x0a, 0x0c, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x44, 0x72, 0x61,
	0x77, 0x49, 0x6d, 0x67, 0x12, 0x17, 0x2e, 0x78, 0x67, 0x72, 0x70, 0x63, 0x64, 0x2e, 0x53, 0x6d,
	0x61, 0x72, 0x74, 0x44, 0x72, 0x61, 0x77, 0x49, 0x6d, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e,
	0x78, 0x67, 0x72, 0x70, 0x63, 0x64, 0x2e, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x44, 0x72, 0x61, 0x77,
	0x49, 0x6d, 0x67, 0x52, 0x73, 0x70, 0x22, 0x28, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x22, 0x22, 0x1d,
	0x2f, 0x66, 0x61, 0x6e, 0x63, 0x79, 0x5f, 0x70, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x2f, 0x73,
	0x6d, 0x61, 0x72, 0x74, 0x5f, 0x64, 0x72, 0x61, 0x77, 0x5f, 0x69, 0x6d, 0x67, 0x3a, 0x01, 0x2a,
	0x42, 0x10, 0x5a, 0x0e, 0x66, 0x61, 0x6e, 0x63, 0x79, 0x5f, 0x70, 0x61, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fancy_painter_proto_rawDescOnce sync.Once
	file_fancy_painter_proto_rawDescData = file_fancy_painter_proto_rawDesc
)

func file_fancy_painter_proto_rawDescGZIP() []byte {
	file_fancy_painter_proto_rawDescOnce.Do(func() {
		file_fancy_painter_proto_rawDescData = protoimpl.X.CompressGZIP(file_fancy_painter_proto_rawDescData)
	})
	return file_fancy_painter_proto_rawDescData
}

var file_fancy_painter_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_fancy_painter_proto_goTypes = []interface{}{
	(*UserLoginReq)(nil),                  // 0: xgrpcd.UserLoginReq
	(*UserInfo)(nil),                      // 1: xgrpcd.UserInfo
	(*UserLoginRsp)(nil),                  // 2: xgrpcd.UserLoginRsp
	(*UserReq)(nil),                       // 3: xgrpcd.UserReq
	(*UserRsp)(nil),                       // 4: xgrpcd.UserRsp
	(*SmartDrawImgReq)(nil),               // 5: xgrpcd.SmartDrawImgReq
	(*SmartDrawImgRsp)(nil),               // 6: xgrpcd.SmartDrawImgRsp
	(*fancy_common.SmartDrawImgTask)(nil), // 7: fancycommon.SmartDrawImgTask
}
var file_fancy_painter_proto_depIdxs = []int32{
	7, // 0: xgrpcd.SmartDrawImgReq.smart_draw_img_task:type_name -> fancycommon.SmartDrawImgTask
	3, // 1: xgrpcd.FancyPainter.GetUser:input_type -> xgrpcd.UserReq
	0, // 2: xgrpcd.FancyPainter.UserLogin:input_type -> xgrpcd.UserLoginReq
	5, // 3: xgrpcd.FancyPainter.SmartDrawImg:input_type -> xgrpcd.SmartDrawImgReq
	4, // 4: xgrpcd.FancyPainter.GetUser:output_type -> xgrpcd.UserRsp
	2, // 5: xgrpcd.FancyPainter.UserLogin:output_type -> xgrpcd.UserLoginRsp
	6, // 6: xgrpcd.FancyPainter.SmartDrawImg:output_type -> xgrpcd.SmartDrawImgRsp
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_fancy_painter_proto_init() }
func file_fancy_painter_proto_init() {
	if File_fancy_painter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fancy_painter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserLoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fancy_painter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fancy_painter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserLoginRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fancy_painter_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fancy_painter_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fancy_painter_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmartDrawImgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fancy_painter_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmartDrawImgRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fancy_painter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fancy_painter_proto_goTypes,
		DependencyIndexes: file_fancy_painter_proto_depIdxs,
		MessageInfos:      file_fancy_painter_proto_msgTypes,
	}.Build()
	File_fancy_painter_proto = out.File
	file_fancy_painter_proto_rawDesc = nil
	file_fancy_painter_proto_goTypes = nil
	file_fancy_painter_proto_depIdxs = nil
}
